import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/components/Navigation'
import Banner from '@/components/ui/Banner'

export const metadata: Metadata = {
	title: 'Medium.',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="relative">
				<Navigation />
				<Banner title="Get unlimited access to the best of Medium for less than $1/week." />
				<main className="container pt-[150px] pb-6">{children}</main>
			</body>
		</html>
	)
}
