import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/components/Navigation'

export const metadata: Metadata = {
	title: 'MyBlogApp.',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="relative">
				<Navigation />
				<main className="container pt-[150px] pb-6">{children}</main>
			</body>
		</html>
	)
}
